### ISSUE TITLE
Issues with fields other than checkboxes

### ISSUE THREAD

**Issue by nathardwick** [lmoffereins/bp-xprofile-field-read-only#1]
Just started using the plugin with BP 2.3.3 and it works exactly as it should with checkboxes but doesn't with drop-downs or text box inputs (they remain editable by the user).

**Comment by lmoffereins** [comment]
Hi @nathardwick, thanks for your feedback. If you're still interested, please try the latest version `1.1.0`. This release removes the `readonly` and `disabled` input attributes and instead removes the marked fields completely from edit contexts (front-end and admin). This fixes the issue where `disabled` fields are not processed by HTML forms and thus updated with empty values. Your issue should now also be fixed.

**Comment by lmoffereins** [comment]
Considering this issue fixed.
